[tool.poe.executor]
type = "poetry"

[tool.poe.tasks.test]
cmd = "pytest -v --pyargs tests"
[tool.poe.tasks.test.env]
_MERGIFY_TEST_NEW_FLAKY_DETECTION = "true"

[tool.poe.tasks.linters]
help = "Run linters"
deps = ["setup"]
default_item_type = "cmd"
sequence = [
  "ruff check .",
  "ruff format --check .",
  "mypy",
  "codespell",
  "yamllint .",
]

[tool.poe.tasks.setup]
help = "Sync poetry virtualenv"
executor = { type = "simple" }
cmd = "./tools/poetry-install.sh"
