name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main
      - devs/**

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          enable-cache: true
          version-file: requirements-uv.txt

      - run: |
          export UV_PYTHON=${{ matrix.python-version }}
          export UV_LOCKED=1
          uv run poe linters
          uv run poe test
          uv build

  codespell:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          enable-cache: true
          version-file: requirements-uv.txt

      - run: |
          export UV_PYTHON=3.14
          export UV_LOCKED=1
          uv run codespell

  semgrep:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep:1.100.0
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Run Semgrep
        run: |
          semgrep --config=auto --error --timeout=15 .
