name: upload release to PyPI
on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ">=3.10"
      - name: Get version
        run: |
          echo "version=$(date +'%Y.%m.%d.%H.%M')" >> "$GITHUB_ENV"
      - name: Tag and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            git tag $version
            git push origin $version
            pip install poetry
            poetry self add poetry-dynamic-versioning[plugin]
            poetry install --sync
            poetry build
            gh release create --generate-notes $version ./dist/*
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
